### PR TITLE
LPS-136040

### PR DESCRIPTION
**Pull request by Odrakir1**
This issue was caused by a missing group id, in this case, the Global group id. The asset was being fetched by the Control Panel's group id only, adding the Global group id in the search solved the problem.

https://issues.liferay.com/browse/LPS-136040

### CODE REVIEW

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by Odrakir1** [comment]
ci:test:relevant

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Hi @wanderlast, any updates on this? The failure above is not related to this pull. Would you be willing to send to @liferay-usm for review if this is ready?

**Comment by wanderlast** [comment]
Hi @patriciajeanperez,

Sorry for the delay, I was out yesterday. I should be able to finish taking a look at this and will forward it most likely later today.

**Comment by wanderlast** [comment]
Forwarded here: https://github.com/liferay-usm/liferay-portal/pull/187

CC: @patriciajeanperez

**Comment by patriciajeanperez** [comment]
Thank you, @wanderlast!

**Pull request closed without merging**
