### PR TITLE
LPS-110418 Prevent NullPointerException from being thrown

### PR DESCRIPTION
**Pull request by kevhlee**
<https://issues.liferay.com/browse/LPS-110418>

Hi @wanderlast,

The issue was that the notification portlet tried to invoke a method on the `userNotificationFeedEntry` variable when it was set to `null`.

* <https://github.com/kevhlee/liferay-portal/blob/4c6f47997f515e43e4ee78f52b5a64df6d9fdcec/modules/apps/notifications/notifications-web/src/main/resources/META-INF/resources/notifications/user_notification_entry.jspf#L55>

When a notification comes from a module that is uninstalled or deactivated, its corresponding `userNotificationFeedEntry` variable is set to `null`, which causes the problem described in [LPS-110418](https://issues.liferay.com/browse/LPS-110418).

With regards,
Kevin

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Source format

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Forwarded here: https://github.com/ChrisKian/liferay-portal/pull/195

**Pull request closed without merging**
