### PR TITLE
LPS-137215

### PR DESCRIPTION
**Pull request by Odrakir1**
The previous behavior when trying to access a private page as a non-logged in user caused a response of _Not Found_. Adding a conditional right before the permission verification to make to user go to the sign in screen solved the issue.

### CODE REVIEW

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by Odrakir1** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:reevaluate:1267401_241

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Please check this one more time looking at the comments I've made and also rebuilding and testing it. For me, I can no longer add a tag or category to an account, but if you can't reproduce this just let me know and I'll try rebuilding again.

**Comment by wanderlast** [comment]
Forwarded to here: https://github.com/ericyanLr/liferay-portal/pull/243

**Pull request closed without merging**
