### PR TITLE
LPS-136040

### PR DESCRIPTION
**Pull request by Odrakir1**
The previous behavior forced the Control Panel group id to be used, because it was stored before the getGroupIds() was called. In addition, the portlet URL's parameter "groupIds" was using that id which led the Selector fetch no tag. A piece of code was removed because it made the fetch use the Site id.

### CODE REVIEW

**Comment by Odrakir1** [comment]
The previous behavior forced the Control Panel group id to be used, because it was stored before the `getGroupIds()` was called. In addition, the portlet URL's parameter "groupIds" was using that id which led the Selector fetch no tag. A piece of code was removed because it made the fetch use the Site id.

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by Odrakir1** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Please check this one more time looking at the comments I've made and also rebuilding and testing it. For me, I can no longer add a tag or category to an account, but if you can't reproduce this just let me know and I'll try rebuilding again.

**Pull request closed without merging**
