### PR TITLE
LPS-117378 Make required categories for web content structures optional when editing default values

### PR DESCRIPTION
**Pull request by kevhlee**
Relevant Tickets
- [LPS-117378](<https://issues.liferay.com/browse/LPS-117378>)
- [PTR-1829](<https://issues.liferay.com/browse/PTR-1829>)

Currently, default values for a web content structure cannot be edited when it has required categories. However, filling any category, required or not, should be optional when editing default values. The requirement should only apply when creating a web content article from the structure.

The issue is that asset entry validations (such as filling out mandatory fields/categories) are performed on a web content structure regardless of whether the user is editing it ("Edit") or editing its default values ("Edit Default Values"). Thus, an exclusion rule for journal articles needs to be added so that journal articles representing structure default values are excluded from asset entry validation. The solution is based on discussion in [PTR-1829](<https://issues.liferay.com/browse/PTR-1829>).

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
Temporarily closing PR to add additional changes.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
See: https://github.com/kevhlee/liferay-portal/pull/5

**Comment by wanderlast** [comment]
Forwarded here: https://github.com/ChrisKian/liferay-portal/pull/245

**Pull request closed without merging**
