### PR TITLE
[NOT TO MERGE] LPS-86455

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @wanderlast

Please *DON'T* send this PR to Brian yet. I'm sending this to you for
further testing; I've checked Video, Images and PDF, but as you're
more familiar with the use case, I think it is better if you could
take a look as well.

I need to solve an additional problem before sending this
upstream. See https://issues.liferay.com/browse/LPS-89482.

I'll CC you in the PR so that you're aware of the progress.

Thanks!

/cc @robertoDiaz

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Hi @adolfopa,

Thanks for looking at this issue and sending this to me! Besides the SF errors, this looks good to me. I'll keep this open while you work on https://issues.liferay.com/browse/LPS-89482 and I'll close it when you forward it on.

**Comment by adolfopa** [comment]
Yep, ignore the SF, this is a WIP :-)

I'm almost finished with the other issue. It may take its time, as I had to make changes across multiple modules (and core). I hope to have this ready by tomorrow morning.

Thanks!

**Comment by adolfopa** [comment]
Hey @wanderlast 

Finally, the other PR was merged. I'll send this today (will CC you).

Thanks!

**Pull request closed without merging**
