### PR TITLE
LPS-136040

### PR DESCRIPTION
**Pull request by Odrakir1**
This issue was caused by a missing group id, in this case, the Global group id. The asset was being fetched by the Control Panel's group id only, adding the Global group id in the search solved the problem.

### CODE REVIEW

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by Odrakir1** [comment]
ci:test:relevant

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
Looks good to me, I'll forward to USM team.

**Pull request closed without merging**
