### PR TITLE
LPS-140333

### PR DESCRIPTION
**Pull request by Odrakir1**
The Color Palette had no tooltip when the user hovered the mouse over the colors, making it hard the for him to distinguish the colors.

# What has been changed?

When hovering the mouse over the colors of the Color Palette, a tooltip the color name is shown.

# Why this change was necessary?

A lack of tooltip affected the UX for the user didn't know the color name.

More details at [LPS-140333](https://issues.liferay.com/browse/LPS-140333)

image

### CODE REVIEW

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by Odrakir1** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
@Odrakir1 Test results look related, could you please take a look? Let me know if you need help evaluating them.

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by Odrakir1** [comment]
ci:reevaluate:1327401_685

**Comment by Odrakir1** [comment]
As an update, I'm checking with QA Echo for analyzing the relevant test. As a mention, Patrick Yoo suggested that: 

> These problems may have been present in upstream but somehow didn’t get revealed until you made your change

**Comment by wanderlast** [comment]
I agree that it's possible, but (like we talked about on Slack), I'd like it if you could let me know how you reached that conclusion. Either by telling me how exactly your fix isn't relevant to this or otherwise.

**Comment by wanderlast** [comment]
ci:test:relevant

**Pull request closed without merging**
