### PR TITLE
LPS-89202: Available Languages setting bug in site settings

### PR DESCRIPTION
**Pull request by nellyliupeng**
**LPS**: [LPS-89202](https://issues.liferay.com/browse/LPS-89202)

**Instance Settings vs Site Settings**
Currently, there is an issue under Site Settings, where the request processes successfully (but does not save the updated languageIds list) when user removes all current available languages (those in the leftList located in display_settings.jsp). Compare this to the behavior under Instance Settings, where user is prevented from removing all languages (or the default language) from the leftList by preventing request from going through and by displaying "You cannot remove a language that is the current default language."

**Solution Approach:**
User should not be allowed to remove all current languages from a site (even in more detail, user should not be allowed to remove the current default language if it's in use) (a reference used: [LPS-41530](https://issues.liferay.com/browse/LPS-41530)). 
Currently, [a check is done](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/GroupLocalServiceImpl.java#L3932) when languageIds list is empty, but there's no followup code that deals when that scenario occurs, which eventually allows for the request to go successfully even when no change was done to the locale attribute and which explains the behavior in LPS-89202. 

This fix throws an exception to prevent the request from going successfully and notifies the user with proper info message. 
Currently, when an user attempts to remove a language that is the default language, the message reads ["Please select a default language among the available languages of the site...[list of languageIds]"](https://github.com/liferay/liferay-portal/blob/master/modules/apps/site/site-admin-web/src/main/resources/META-INF/resources/site/display_settings.jsp#L95). However, this is a little nonintuitive as the UI would still display the language that was attempted to be removed included as an option. Message was replaced to "You cannot remove a language that is the current default language."

### CODE REVIEW

**Comment by nellyliupeng** [comment]
ci:test:sf

**Comment by nellyliupeng** [comment]
ci:test:relevant

**Comment by nellyliupeng** [comment]
ci:stop

**Comment by nellyliupeng** [comment]
ci:test:sf

**Comment by nellyliupeng** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Discussed related test failures. Closing so it can be resent with fixes.

**Pull request closed without merging**
