### PR TITLE
LPS-119945 Liferay requests combo resources when cdn.dynamic.resources.enabled=false

### PR DESCRIPTION
**Pull request by kevhlee**
LPS Ticket: <https://issues.liferay.com/browse/LPS-119945>

The issue is that the portal does not check the setting `cdn.dynamic.resources.enabled` before constructing combo URLs. Prior, the portal would prepend the CDN host URL regardless of this setting. Thus, this pull request adds checking so that portal checks this setting and only attaches the CDN host URL if enabled.

Let me know if you have any questions.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
Hi @kevhlee,

This mostly looks good, but I was wondering if there's a reason you opted to put this into ThemeDisplay instead of just using PortalUtil.isCDNDynamicResourcesEnabled()?

**Comment by kevhlee** [comment]
Hey @wanderlast,

I initially tried to use `PortalUtil.isCDNDynamicResourcesEnabled()` to perform the check but SF started to complain. I also tried `_portal.isCDNDynamicResourcesEnabled()` but the method throws a `PortalException`, so I would have to place the code in a try-catch block, which would have been okay. But then I noticed that `PortalUtil.isCDNDynamicResourcesEnabled()` is called when the theme display is initialized:

https://github.com/wanderlast/liferay-portal/blob/2916d06ff06783160cf4bf3e3bb16489d6ac2b40/portal-impl/src/com/liferay/portal/events/ServicePreAction.java#L798-L799

I thought it would be convenient for future use to allow the theme display to indicate this setting.

**Comment by wanderlast** [comment]
Hi @kevhlee,

Ah, I see. I was referring to using:

`public boolean isCDNDynamicResourcesEnabled(long companyId);`

It doesn't throw an exception and companyId is already easily retrievable from ThemeDisplay. I'm mostly concerned about backporting this when the time comes (I'm not sure how much the ER team will like adding new API esp since API technically already exists for it), but since you think having it available in ThemeDisplay will help I'll forward this.

**Comment by kevhlee** [comment]
Hey @wanderlast,

That's true. You do have a point about the backport. I don't mind using `isCDNDynamicResourcesEnabled(long companyId)` instead. I'll close this pull and send a new pull request with your suggestion.

**Comment by kevhlee** [comment]
New pull request: <https://github.com/wanderlast/liferay-portal/pull/77>

**Pull request closed without merging**
