### PR TITLE
LPS-122681, LPS-122683

### PR DESCRIPTION
**Pull request by kevhlee**
**Ticket:**
<https://issues.liferay.com/browse/LPS-122681>
<https://issues.liferay.com/browse/LPS-122683>

**Notes:**
For [LPS-122681](https://issues.liferay.com/browse/LPS-122681), the wrong scope is used when selecting a predefined value for a web content field due to the use of `themeDisplay.getURLControlPanel()`. We need to use `themeDisplay.getLayoutRelativeControlPanelURL()`, as seen throughout `custom_fields.js`:

- <https://github.com/liferay/liferay-portal/blob/7.3.5-ga6/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/custom_fields.js#L365>

For [LPS-122683](https://issues.liferay.com/browse/LPS-122683), the predefined value cannot be set for the web content structure because`itemSelectedEventName` is incorrect; the event handler is expecting `selectDocumentLibrary` rather than `selectContent`, as seen here:

* <https://github.com/liferay/liferay-portal/blob/7.3.5-ga6/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/custom_fields.js#L626>

Let me know if you have any questions.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @kevhlee, 
The second issue is reported here https://issues.liferay.com/browse/LPS-122683

**Comment by kevhlee** [comment]
Hi @Tim-Cao, thanks for mentioning the ticket!

@wanderlast, I will be updating this pull request and commit messages to include [LPS-122683](https://issues.liferay.com/browse/LPS-122683).

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
Looks good to me, forwarded here: https://github.com/ChrisKian/liferay-portal/pull/264

**Pull request closed without merging**
