### PR TITLE
LPS-138140

### PR DESCRIPTION
**Pull request by Odrakir1**
The issue was causing a misplacement of the tooltip text when the screen was smaller than 1250px. I have changed the tooltip alignment value for that it won't get affected when the screen is shrinked.

### CODE REVIEW

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by Odrakir1** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Hi @Odrakir1, could you please write an explanation for this issue as well as an explanation for your solution? Thank you.

**Comment by wanderlast** [comment]
Forwarded here: https://github.com/liferay-frontend/liferay-portal/pull/1450

**Pull request closed without merging**
