### PR TITLE
LPS-111718 Prevent calendar booking's asset fields from being overwritten

### PR DESCRIPTION
**Pull request by kevhlee**
Ticket: https://issues.liferay.com/browse/LPS-111718

Hi @wanderlast,

When the user updates a calendar booking using the pop-up box, a new booking is created with the update and the old one is deleted, as seen [here](https://github.com/kevhlee/liferay-portal/blob/LPS-111718/modules/apps/calendar/calendar-service/src/main/java/com/liferay/calendar/service/impl/CalendarBookingLocalServiceImpl.java#L1350-L1421). The issue was that the assets of the old booking were not stored in the service context and therefore not passed to the new booking. The service context is used to update the asset fields of calendar bookings, as seen [here](https://github.com/kevhlee/liferay-portal/blob/LPS-111718/modules/apps/calendar/calendar-service/src/main/java/com/liferay/calendar/service/impl/CalendarBookingLocalServiceImpl.java#L260-L264). To fix this issue, I made sure that the assets of the old booking are stored in the service context in `CalendarPortlet.java` before the booking is updated.  

With regards,
Kevin

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
Making updates to this PR. Will reopen.

**Comment by kevhlee** [comment]
SF

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
Closing based on manual testing per discussion on Slack.

**Pull request closed without merging**
