### PR TITLE
LPS-139049 | FieldsSelectorDropdown redirects to blank page if Enter is pressed.

### PR DESCRIPTION
**Pull request by Odrakir1**
When using the FieldsSelectorDropdown component, which uses ClayDropDown.Search, the user is redirected to a blank page inside the Portal he types _Enter_ inside the text area. Preventing the form from being submitted by passing a onForm event to the component solves the issue.

Steps to Reproduce:

1. Navigate to Remote Apps or Custom Elements
2. Add asset
3. Click on carrot at top of last column of asset list
4. Type any string in search bar
5. Hit Enter key

# What have been changed?

Now, a blank page won't shown up if the user hits _Enter_

# Why this fix was necessary?

The previous behavior was unintended and didn't make sense, if the user was being redirected to a blank page losing the progress what if he was doing, in this context, searching for a filter.

[You can find more details here: LPS-139049](https://issues.liferay.com/browse/LPS-139049)

Gif of current behavior

### CODE REVIEW

**Comment by Odrakir1** [comment]
ci:test:sf

**Comment by Odrakir1** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Hi @Odrakir1,

Thanks for taking the time to write your PR! It's much easier for me to follow now. Could you please elaborate on what you mean by "Preventing the for form from being submitted by passing a onForm event to the component solves the issue". What for form?

**Comment by Odrakir1** [comment]
> Hi @Odrakir1,
> 
> Thanks for taking the time to write your PR! It's much easier for me to follow now. Could you please elaborate on what you mean by "Preventing the for form from being submitted by passing a onForm event to the component solves the issue". What for form?

Hey Lianne. Sure! The [FieldsSelectorDropdown](https://github.com/liferay/liferay-portal/blob/b61478730f9e06b8826633e08c9caf0b7292318d/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/data_set_display/views/table/FieldsSelectorDropdown.js#L66) component has a [Search](https://github.com/liferay/clay/blob/fca2ea2e774d4eaed75732212eae9596dc1972e0/packages/clay-drop-down/src/Search.tsx#L43-L45) component inside it, and this is wrapped by a form tag which receives some props, and it was this form I passed the _onForm_ function to.

**Comment by wanderlast** [comment]
As an update, I should be able to finish reviewing this tomorrow.

**Comment by wanderlast** [comment]
Ok, was able to finish verifying a question I had on this one. Re-running test suite just to make sure it's still ok with upstream and then will (hopefully) forward later today.

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Forwarded here: https://github.com/liferay-frontend/liferay-portal/pull/1578

**Pull request closed without merging**
