### PR TITLE
LPS-110278 Update parent IDs of draft layouts

### PR DESCRIPTION
**Pull request by kevhlee**
<https://issues.liferay.com/browse/LPS-110278>

Hey @wanderlast,

When the parent of a content page layout is updated, the parent of the corresponding draft layout must also be updated. However, this was not the case. Thus, draft layouts would reference the wrong parent layouts (potentially deleted ones). The layout permission checker looks at the parent of each layout, including draft layouts, as seen in the following:

* <https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/permission/LayoutPermissionImpl.java#L268-L279>.

Because of this, the layout permission checker can potentially look for a deleted layout and throw a `NoSuchLayoutException`, which was causing the problem described in [LPS-110278](https://issues.liferay.com/browse/LPS-110278).

With regards,
Kevin

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
This looks good to me, but latest Master broke content pages (the publish button no longer exists), so I can't test it just yet. I'll try again Monday and will hopefully be able to push it forward then.

**Comment by wanderlast** [comment]
Forwarded here: https://github.com/ChrisKian/liferay-portal/pull/194

**Pull request closed without merging**
