### PR TITLE
LPS 88862: Incorrect portlet title text at "Forgot Password" and "Create Account"

### PR DESCRIPTION
**Pull request by nellyliupeng**
**LPS**: https://issues.liferay.com/browse/LPS-88862

Currently, "Sign In" is being used as portlet title as it is the display name for the Login Portlet.
However, there is an issue as the portlet title does not update when action commands such as "create account" and "forgot Password" within the portlet are called. This fix was made to update the portlet title accordingly.

### CODE REVIEW

**Comment by nellyliupeng** [comment]
ci:test:sf

**Comment by nellyliupeng** [comment]
ci:test:relevant

**Comment by nellyliupeng** [comment]
ci:stop

**Comment by nellyliupeng** [comment]
ci:test:sf

**Comment by nellyliupeng** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Looks good! Forwarded here: https://github.com/ChrisKian/liferay-portal/pull/83

**Pull request closed without merging**
