### PR TITLE
LPS-91528 Remove ckeditor autoparagraph configuration

### PR DESCRIPTION
**Pull request by nellyliupeng**
https://issues.liferay.com/browse/LPS-91528

**Issue:**
Portlets that can use CKEditor are affected with additional space `"\n"` added when user adds html tags within a non-paragraph content. Space is added as it goes thru antisamy.
ie.    a**b**c ---> a**b** c
AlloyEditor does not face same issue as user's input is automatically enclosed in `<p>` tags. (However, notice that if you deliberately remove the `<p>` tags in the Code View then the issue will be reproduced).

**Solution:**
Have CKEditor enclose content in paragraph (same behavior as current AlloyEditor).
Testings were done with [ckeditor-dev](https://github.com/ckeditor/ckeditor-dev) and [liferay-ckeditor](https://github.com/liferay/liferay-ckeditor) by itself and they do not reproduce issue as they autoparagraph content.

The [CKEditor doc](https://docs-old.ckeditor.com/ckeditor_api/symbols/CKEDITOR.config.html#.autoParagraph) also includes this note about `config.autoParagraph` (default value is `true`):

> Note: Changing the default value might introduce unpredictable usability issues.

### CODE REVIEW

**Comment by nellyliupeng** [comment]
ci:test:sf

**Comment by nellyliupeng** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Hi @nellyliupeng,
The test failures don't seem like they should be related, but I'm also not currently seeing them on any other test runs right now. It's possible it may simply need to be rebased to a later master. I'll be rebasing this and running the relevant test on it again tomorrow and will hopefully be able to pass it on then.

**Comment by nellyliupeng** [comment]
Hi @wanderlast,
Thank you! I was curious about those results too. Hopefully that resolves the issue. Thank you again!

**Comment by wanderlast** [comment]
Looks like they're passing here: https://github.com/wanderlast/liferay-portal/pull/26#issuecomment-470242758

Forwarding to Chris: https://github.com/ChrisKian/liferay-portal/pull/111

**Pull request closed without merging**
