### PR TITLE
LPS-87629 Added additional check when getting date range

### PR DESCRIPTION
**Pull request by nellyliupeng**
LPS: https://issues.liferay.com/browse/LPS-87629

See previous PR for description of bug:  https://github.com/wanderlast/liferay-portal-ee/pull/13

This PR adds an additional check when retrieving date range, which is later added to the query used to retrieve ADTs

### CODE REVIEW

**Comment by nellyliupeng** [comment]
ci:test:sf

**Comment by nellyliupeng** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:open

**Comment by nellyliupeng** [comment]
ci:test:sf

**Comment by nellyliupeng** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Looks good! Reviewed and forwarded to Chris: https://github.com/ChrisKian/liferay-portal/pull/71

**Pull request closed without merging**
